FROM node:18-alpine as build

WORKDIR /app

COPY package.json package-lock.json ./
COPY . .

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist/zoopervisor-client/ /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf