version: '3'

services:
  zoopervisor-api:
    image: probstin09/zoopervisor-api:latest
    ports:
      - "8080:8080"
    env_file: ./api/.env
    networks:
      - zoopervisor-network

  zoopervisor-client:
    image: probstin09/zoopervisor-client:latest
    ports:
      - "4200:4200"
    networks:
      - zoopervisor-network

networks:
  zoopervisor-network:
    driver: bridge
