server.servlet.context-path: /api

exchange.client:
  name: exchange-client
  apiKey: ${EXCHANGE_API_KEY}
  apiUrl: ${EXCHANGE_API_URL}
  
catalog.client:
  name: catalog-client
  apiKey: ${CATALOG_API_KEY}
  apiUrl: ${CATALOG_API_URL}